language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
  - windows
before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get -qq update
      sudo apt-get install -y libudev-dev
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      mkdir glslang
      cd glslang
      wget https://github.com/KhronosGroup/glslang/releases/download/7.11.3214/glslang-master-linux-Release.zip
      unzip -u -q glslang-master-linux-Release.zip
      cd ..
      export PATH=${TRAVIS_BUILD_DIR}/glslang/bin:$PATH
      glslangValidator --version
    fi
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x tests/diff_shaders && ./tests/diff_shaders; fi
  - cargo test --verbose --features opengl
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cargo test --verbose --features vulkan --release; fi
