[package]
name = "coffee"
version = "0.1.1"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2018"
description = "An opinionated 2D game engine focused on simplicity, explicitness, and type-safety"
license = "MIT"
repository = "https://github.com/hecrj/coffee"
documentation = "https://docs.rs/coffee"
readme = "README.md"
keywords = ["game", "engine", "2D", "graphics", "coffee"]
categories = ["game-engines"]
exclude = ["images/*"]

[badges]
maintenance = { status = "actively-developed" }

[package.metadata.docs.rs]
features = ["opengl", "debug"]

[features]
default = ["opengl"]
opengl = ["gfx", "gfx_core", "glutin", "gfx_device_gl", "gfx_window_glutin", "gfx_glyph", "gfx_winit"]
vulkan = ["wgpu", "wgpu/vulkan"]
metal = ["wgpu", "wgpu/metal"]
dx11 = ["wgpu", "wgpu/dx11"]
dx12 = ["wgpu", "wgpu/dx12"]
debug = []

[dependencies]
image = "0.21"
nalgebra = "0.18"

# gfx (OpenGL)
gfx = { version = "0.18", optional = true }
gfx_core = { version = "0.9", optional = true }
glutin = { version = "0.20", optional = true }
gfx_device_gl = { version = "0.16", optional = true }
gfx_window_glutin = { version = "0.30", optional = true }
gfx_glyph = { version = "0.14", optional = true }
gfx_winit = { package = "winit", version = "0.19", optional = true }

# wgpu (Vulkan, Metal, D3D)
wgpu = { version = "0.2", optional = true }

# controller support
gilrs = "0.7.1"

[dev-dependencies]
# Example dependencies
rand = "0.6"
rayon = "1.0"
